### ISSUE TITLE
Unable to install package in Xamarin Forms App

### ISSUE THREAD

**Issue by aherrick** [jcheng31/ForecastPCL#16] opened 2016-08-25 01:59 UTC
Trying to Install in File => New Xamarin Forms App (iOS/Android/UWP) simply fails.

Thanks for the work though looks nice!

**Comment by jcheng31** [comment] 2016-08-27 12:47
Hey @aherrick - I was able to reproduce this in a clean Xamarin Forms app, and it seems the issue is because NuGet tries to install `Microsoft.Bcl.Build` version 1.0.14 when resolving dependencies; this doesn't seem to play nicely with Xamarin.

On the bright side, the latest version of that library (1.0.21) can be installed, after which ForecastPCL should install without issue. Could you try manually installing that first and trying ForecastPCL again?

**Closed** 2016-09-27 14:37 UTC
